[리팩토링] 포스터 인터렉션 변경
pigs-pango-team/gg-pigs-web pull request #147
Opened 2021-06-04 02:45 UTC by kkwongs

**[리팩토링] 포스터 인터렉션 변경**

1. sm ( ~ 599px): click 하면 링크 버튼만 나오도록 하였습니다.
2. md (600px ~ 1263px): click 하면 상세정보가 나오도록 하였습니다.
3. lg (1264px ~ ): hover 하면 상세정보가 나오도록 하였습니다.

Closes #141

2021-06-05 04:00 UTC, hjjae2 requested changes
확인했습니다! 고생하셨습니다. 👍

2021-06-05 04:00 UTC, hjjae2 commented on store/index.js
> +    link: require('~/static/icon/link.svg'),
`link` 라는 것이 혹시 어떤 link 이미지 인가요 ??

link는 너무 포괄적인 것 같아서, 혹시 조금 더 구체적인 변수명을 사용하는 것은 어떻게 생각하시나요 ??

(단순히 의견이 궁금하여 코멘트 남기겠습니다! 반영이 되지 않아도 좋습니다!)

2021-06-05 04:00 UTC, hjjae2 commented on components/PosterBox.vue
> +      />
저번에 잠깐 이야기가 나왔던 부분인 것 같은데요!!

위의 `div v-if="dayMode"`, 아래의 `div v-else` 에서의 차이점이
`icon/empty-poster-default.svg`, `icon/empty-poster-default-dark.svg` 이 부분에서만 있는 것 같은데요!

이 부분을 computed 로 적용하면 하나의 `div` 안에서 해결할 수 있지 않을까? 라는 생각이 드는데, 어떻게 생각하시나요 ??

> 이 부분은 조금 많은 코드의 중복이 있어서, 개선하고 넘어가면 더욱 좋을 것 같습니다!! 👍

2021-06-05 04:00 UTC, hjjae2 commented on components/PosterBox.vue
> +        posterHeight: '200',
뒷단에서도 포스터 사이즈 변경이 필요하겠군요!

확인하였습니다!

2021-06-29 07:44 UTC, kkwongs commented on components/PosterBox.vue
> +      />
코드를 다시 확인해보니 가능할 것 같습니다. 수정하겠습니다!

2021-06-29 07:44 UTC, kkwongs commented on components/PosterBox.vue
> +        posterHeight: '200',
아하! 그렇게 해야될 것 같습니다!

2021-06-29 07:44 UTC, kkwongs commented on store/index.js
> +    link: require('~/static/icon/link.svg'),
좋은 의견 감사합니다. 수정하겠습니다!

2021-06-29 13:32 UTC, hjjae2 approved these changes
확인완료했습니다! 고생하셨습니다!

2021-06-29 13:32 UTC, hjjae2 commented on components/PosterBox.vue
> +  },
👍

2021-06-29 13:32 UTC, hjjae2 commented on components/PosterBox.vue
> +          :src="emptyPosterBoxDefault"
이런 것들도 다 변수처리로 변경하였군요! 좋은 것 같아요!👍

2021-06-29 13:32 UTC, hjjae2 commented on components/PosterBox.vue
> +    },
👍

2021-06-30 10:41 UTC, merged